r_packages:
    - covr
    - pdftools
language: r
warnings_are_errors: true
sudo: true
dist: trusty

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libapparmor-dev
      - libpoppler-cpp-dev

env:
    global:
    - R_CHECK_ARGS="--no-build-vignettes"
after_success:
  - Rscript -e 'library(covr); codecov()'
