r_packages:
    - covr
    - pdftools
language: r
warnings_are_errors: true
sudo: true
dist: trusty

apt_packages:
  - libssh2-1-dev
  - libapparmor-dev
  - libpoppler-cpp-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6
        - CC=gcc-6
        - CXX=g++-6
        
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 500
  - mkdir -p ~/.R
  - echo "VER=-6" > ~/.R/Makevars
  - echo "Q0M9Z2NjJChWRVIpIC1zdGQ9YzExIApDWFg9ZysrJChWRVIpClNITElCX0NYWExEPWcrKyQoVkVSKQpGQz1nZm9ydHJhbgpGNzc9Z2ZvcnRyYW4K" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars

# before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update
#  - sudo apt-get install gcc-5
#  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
#  - sudo update-alternatives --query gcc
#  - gcc --version
#  - sudo apt-get install g++-5
#  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
#  - g++ --version
#  - sudo apt-get install gfortran-5
#  - sudo unlink /usr/bin/gfortran && sudo ln -s /usr/bin/gfortran-5 /usr/bin/gfortran
#  - gfortran --version


env:
    global:
    - R_CHECK_ARGS="--no-build-vignettes"
after_success:
  - Rscript -e 'library(covr); codecov()'
