r_packages:
    - covr
    - knitr
    - rmarkdown

language: r
sudo: true

r_binary_packages:
    - testthat

env:
    global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
    - bash <(curl -s https://codecov.io/bash)