r_packages:
    - covr
    - pdftools
language: r
warnings_are_errors: true
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - libapparmor-dev
      - libpoppler-cpp-dev
      - libssh2-1-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CC=gcc=7
        - CXX=g++-7

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-7 100
  - mkdir -p ~/.R
  - echo "VkVSPS03CkNDPWdjYyQoVkVSKSAtc3RkPWMxMSAKQ1hYPWcrKyQoVkVSKQpTSExJQl9DWFhMRD1nKyskKFZFUikKRkM9Z2ZvcnRyYW4KRjc3PWdmb3J0cmFuCg==" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars

#  - Rscript -e 'install.packages("git2r")'

# before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update
#  - sudo apt-get install gcc-5
#  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
#  - sudo update-alternatives --query gcc
#  - gcc --version
#  - sudo apt-get install g++-5
#  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
#  - g++ --version
#  - sudo apt-get install gfortran-5
#  - sudo unlink /usr/bin/gfortran && sudo ln -s /usr/bin/gfortran-5 /usr/bin/gfortran
#  - gfortran --version


env:
    global:
    - R_CHECK_ARGS="--no-build-vignettes"
after_success:
  - Rscript -e 'library(covr); codecov()'
